First attempt to connect to Firebase.
Refusing to connect due to error with Google Play Service Version This should be imported from "apply plugin: 'com.google.gms.google-services'" but it doesn't appear to be.
I have tried to move the Firebase and GSM implentations around to try to get it working but it doesn't seem to be behaving.
I believe this is because this is an instant app, when I mannual add the metadata tag with the error to the manifest studio seems to think the path exist and doesn't highlight it as an error but when compiling I still get the error.

Error:
error: resource integer/google_play_services_version (aka com.remind.wsedlacek.forgetmenot.app:integer/google_play_services_version) not found.
Message{kind=ERROR, text=error: resource integer/google_play_services_version (aka com.remind.wsedlacek.forgetmenot.app:integer/google_play_services_version) not found., sources=[/Volumes/MacOS-Data/Home/wsedlacek/Devolpement/ForgetMeNot/android/base/build/intermediates/manifests/full/feature/debug/AndroidManifest.xml:75], original message=, tool name=Optional.of(AAPT)}

Code:
<meta-data
    android:name="com.google.android.gms.version"
    android:value="@integer/google_play_services_version" />